# double.py

riddles = [
    {"riddle": "Ladkiyon ki aisi kaun si cheez hai jo shaadi ke baad humesha ke liye badal jaati hai?", "answer": "surname"},
    {"riddle": "Vo kya hai jo khada ho toh chhota lagta hai, aur baitho toh bada lagta hai?", "answer": "pair"},
    {"riddle": "Aisa kaun sa kaam hai jo kunwari ladkiyan nahi kar sakti hain?", "answer": "maang bharna"},
    {"riddle": "Ladke ne ladki ki aage se li aur peeche se li... batao kya? (Soch badlo!)", "answer": "photo"},
    {"riddle": "Woh kya hai jo raat ko aapke bistar par bada aur lamba ho jata hai?", "answer": "andhera"},
    {"riddle": "Ladkiyon ka aisa kaun sa ang hai jo garmi ho ya sardi, humesha geela hi rehta hai?", "answer": "jeebh"},
    {"riddle": "Vo kya hai jo andar jaate waqt sakht hota hai aur bahar aate waqt naram aur geela ho jata hai?", "answer": "chingum"},
    {"riddle": "Ek aisi cheez jo ladke chupakar chalte hain aur ladkiyan dikhakar chalti hain?", "answer": "purse"},
    {"riddle": "Ladki ki aisi kaun si cheez hai jismein ungli daalne par paani nikalta hai?", "answer": "aankh"},
    {"riddle": "Vo kya hai jo ladkiyan pehli baar karwati hain toh chilla uththi hain aur khoon bhi nikalta hai?", "answer": "kaan chhedna"},
    {"riddle": "Ladka ladki ke upar leta hota hai aur dono aapas mein ragadte hain, batao kya?", "answer": "cycle"},
    {"riddle": "Vo kya hai jo gol hai, chhota hai, aur ladkiyan use apne munh mein lena pasand karti hain?", "answer": "golgappa"},
    {"riddle": "Ladkiyon ki aisi kaun si cheez hai jo hum pakad sakte hain par chhu nahi sakte?", "answer": "awaaz"},
    {"riddle": "Vo kya hai jo niche se pakadkar upar kheenchne par bada ho jata hai aur baaki sab thandak paate hain?", "answer": "chata"},
    {"riddle": "Aisi kaun si cheez hai jo ladkiyan saal mein sirf ek hi baar pehanti hain?", "answer": "rakhi"},
    {"riddle": "Vo kya hai jo gol-gol ghoomta hai aur dono ke beech mein ghuskar maze deta hai?", "answer": "lattu"},
    {"riddle": "Ladkiyon ki aisi kaun si jagah hai jahan baal hote hain par log dekh nahi paate?", "answer": "sir ke baal"},
    {"riddle": "Vo kya hai jo subah sakht hota hai par din bhar kaam karne ke baad dhingra ho jata hai?", "answer": "insan"},
    {"riddle": "Ladkiyon ke badan ka kaun sa hissa sabse zyaada garam hota hai?", "answer": "dimag"},
    {"riddle": "Vo kya hai jise aage se bhagwan ne banaya aur peeche se insaan ne?", "answer": "bailgadi"},
    {"riddle": "Ladki apne saare kapde kab utarti hai?", "answer": "sukhne ke baad"},
    {"riddle": "Vo kaun si cheez hai jise ladkiyan bada shaunk se chupti hain aur munh mein daalti hain?", "answer": "lollipop"},
    {"riddle": "Ladka aur ladki raat ko akele mein ek dusre ke sath kya karte hain?", "answer": "baatein"},
    {"riddle": "Vo kya hai jo gol hai aur ladkiyan use apne haath mein lekar hilana pasand karti hain?", "answer": "choori"},
    {"riddle": "Aisi kaun si cheez hai jo pehle toh choti hoti hai par paani daalne par badi ho jaati hai?", "answer": "sabun"},
    {"riddle": "Ladkiyon ke paas aisi kaun si cheez hai jo gol hai par gend nahi?", "answer": "bindi"},
    {"riddle": "Vo kya hai jo andar daalne par dard hota hai par baad mein maza aata hai?", "answer": "jhumka"},
    {"riddle": "Aisa kaun sa kaam hai jise karne par sabhi ko rona aata hai par maza bhi aata hai?", "answer": "pyaaz kaatna"},
    {"riddle": "Ladkiyan apne dono haathon se kis cheez ko pakadkar hilati hain?", "answer": "jhoola"},
    {"riddle": "Vo kya hai jo ladkon ka chhota hota hai aur shadi ke baad ladkiyon ka bada ho jata hai?", "answer": "surname"},
    {"riddle": "Aisi kaun si cheez hai jise jitna andar daaloge utna hi maza aayega?", "answer": "sui dhaga"},
    {"riddle": "Ladkiyan roz subah uthkar sabse pehle kis cheez ko apne munh mein leti hain?", "answer": "brush"},
    {"riddle": "Vo kya hai jo pehle sakht hota hai par munh mein daalne par pighal jata hai?", "answer": "ice cream"},
    {"riddle": "Ladka ladki ko pehli baar dekhkar kya sochta hai?", "answer": "naam"},
    {"riddle": "Vo kya hai jo gol hai, laal hai aur ladkiyan use dabana pasand karti hain?", "answer": "tamatar"},
    {"riddle": "Ladkiyon ki aisi kaun si jagah hai jo humesha kaali hoti hai?", "answer": "parchhai"},
    {"riddle": "Vo kya hai jo humesha niche se upar ki taraf khada hota hai aur sab roshni paate hain?", "answer": "khamba"},
    {"riddle": "Ladke apni patni ki kaun si cheez humesha chhu sakte hain par maata ki nahi?", "answer": "pair"},
    {"riddle": "Vo kya hai jo andar jaate waqt bada hota hai par bahar aate waqt chhota ho jata hai?", "answer": "baraf"},
    {"riddle": "Ladkiyon ka aisa kaun sa ang hai jo har do mahine mein badal jata hai?", "answer": "eyebrow"},
    {"riddle": "Vo kya hai jo bina haath-pair ke bhi ladki ke upar chadhta hai?", "answer": "gussa"},
    {"riddle": "Aisi kaun si cheez hai jo khadi ho toh choti aur baitho toh badi lagti hai?", "answer": "pair"},
    {"riddle": "Vo kya hai jo dono taango ke beech mein rehta hai aur gaadi chalane ke kaam aata hai?", "answer": "break"},
    {"riddle": "Ladkiyon ka aisa kaun sa hissa hai jise hum kha sakte hain?", "answer": "ladyfinger"},
    {"riddle": "Vo kya hai jise poora andar daalne par hi aaram milta hai?", "answer": "neend"},
    {"riddle": "Aisi kaun si cheez hai jo ladka pehli baar karta hai toh dar lagta hai par baad mein maza aata hai?", "answer": "driving"},
    {"riddle": "Vo kya hai jo gol hai aur har insaan ke paas do hote hain par milte nahi?", "answer": "gala"},
    {"riddle": "Ladkiyan apne kapde kab badalti hain?", "answer": "gande hone par"},
    {"riddle": "Vo kya hai jo chhota ho toh maza nahi aata, bada ho toh sab khush hote hain?", "answer": "makan"},
    {"riddle": "Ladkiyon ka kaun sa ang sabse pavitra mana jata hai?", "answer": "dimag"},
    {"riddle": "Aisi kaun si cheez hai jo shadi ke baad har pati ko apni patni ko deni padti hai?", "answer": "paisa"},
    {"riddle": "Vo kya hai jo gol hai aur dono taango ke beech mein ghoomta hai?", "answer": "tyre"},
    {"riddle": "Ladkiyon ki aisi kaun si cheez hai jo humesha lambi hoti hai?", "answer": "choti"},
    {"riddle": "Vo kya hai jo aage se gol aur peeche se lamba hota hai?", "answer": "chammach"},
    {"riddle": "Ladka ladki ke sath pehli baar kya karta hai?", "answer": "dosti"},
    {"riddle": "Vo kya hai jo sakht hone par pakda jata hai aur naram hone par chhod diya jata hai?", "answer": "loha"},
    {"riddle": "Aisi kaun si jagah hai jahan ladkiyan akele jana pasand nahi karti?", "answer": "andhera"},
    {"riddle": "Vo kya hai jo gol hai aur ladkiyan use apni ungli mein pehanti hain?", "answer": "angoothi"},
    {"riddle": "Ladkiyon ke kapdon mein aisi kaun si jagah hai jahan kuch nahi hota?", "answer": "pocket"},
    {"riddle": "Vo kya hai jo raat ko sabka khada ho jata hai?", "answer": "dhyan"},
    {"riddle": "Ladkiyon ki kaun si cheez humesha garam rehti hai?", "answer": "chai"},
    {"riddle": "Vo kya hai jo andar jaate hi roshni kar deta hai?", "answer": "diya"},
    {"riddle": "Aisi kaun si cheez hai jise ladkiyan pehanti hain par dikhati nahi?", "answer": "muskaan"},
    {"riddle": "Vo kya hai jo lamba hai, patla hai aur ladkiyan use apne baalo mein lagati hain?", "answer": "pin"},
    {"riddle": "Ladkiyon ka kaun sa roop sab dekhte hain par pati nahi dekh pata?", "answer": "vidhwa roop"},
    {"riddle": "Vo kya hai jo gol hai aur dono haathon se dabaya jata hai?", "answer": "ball"},
    {"riddle": "Aisi kaun si cheez hai jo pehle sakht hoti hai par garam paani mein daalne par naram ho jaati hai?", "answer": "maggi"},
    {"riddle": "Ladkiyon ke paas aisi kaun si cheez hai jise koi chura nahi sakta?", "answer": "gyan"},
    {"riddle": "Vo kya hai jo sakht hai par munh mein jaate hi paani ban jata hai?", "answer": "batasha"},
    {"riddle": "Ladkiyan apne dono per kab kholti hain?", "answer": "chalte waqt"},
    {"riddle": "Vo kya hai jo lamba hai aur dono taango ke beech mein latakta hai?", "answer": "jhadu"},
    {"riddle": "Aisi kaun si cheez hai jo bina aag ke hi garam ho jaati hai?", "answer": "gussa"},
    {"riddle": "Vo kya hai jo gol hai aur ladkiyan use apne face par lagati hain?", "answer": "cream"},
    {"riddle": "Ladkiyon ke kapde kab sabse chote hote hain?", "answer": "bachpan mein"},
    {"riddle": "Vo kya hai jo andar jaate hi sab beh jata hai?", "answer": "aansu"},
    {"riddle": "Aisi kaun si cheez hai jise ladkiyan bada lambe samay tak chabati hain?", "answer": "chingum"},
    {"riddle": "Vo kya hai jo gol hai aur kitchen mein humesha garam rehta hai?", "answer": "tawa"},
    {"riddle": "Ladkiyon ke paas aisi kaun si cheez hai jo ladkon se chhoti hoti hai?", "answer": "hath"},
    {"riddle": "Vo kya hai jo raat ko bada hota hai aur din mein chhota?", "answer": "andhera"},
    {"riddle": "Aisi kaun si cheez hai jo tootne par hi sabko maza deti hai?", "answer": "patang"},
    {"riddle": "Vo kya hai jo lamba hai aur dono haathon se pakadkar hilaya jata hai?", "answer": "jhoola"},
    {"riddle": "Ladkiyon ki kaun si cheez humesha saaf rehti hai?", "answer": "nazar"},
    {"riddle": "Vo kya hai jo sakht hota hai par pani daalne par naram ho jata hai?", "answer": "matti"},
    {"riddle": "Aisi kaun si jagah hai jahan ladkiyan jana pasand karti hain par ladke nahi?", "answer": "beauty parlour"},
    {"riddle": "Vo kya hai jo gol hai aur dono taango ke beech chalta hai?", "answer": "cycle"},
    {"riddle": "Ladkiyon ke paas aisi kaun si cheez hai jo subah aati hai aur shaam ko chali jaati hai?", "answer": "dhup"},
    {"riddle": "Vo kya hai jo lamba hai aur ladkiyan use apne sir par lagati hain?", "answer": "ribbon"},
    {"riddle": "Aisi kaun si cheez hai jo pehle toh chhoti hoti hai par khinchne par badi ho jaati hai?", "answer": "rubber"},
    {"riddle": "Vo kya hai jo gol hai aur ladkiyan use apni naak mein pehanti hain?", "answer": "nathni"},
    {"riddle": "Ladkiyon ke kapdon mein aisi kaun si cheez hai jo khulti aur band hoti hai?", "answer": "chain"},
    {"riddle": "Vo kya hai jo lamba hai aur kitchen mein kaam aata hai?", "answer": "belan"},
    {"riddle": "Aisi kaun si cheez hai jo har pati apni patni ko raat ko deta hai?", "answer": "takiya"},
    {"riddle": "Vo kya hai jo gol hai aur ladkiyan use apne peron mein pehanti hain?", "answer": "payal"},
    {"riddle": "Ladkiyon ke paas aisi kaun si cheez hai jo humesha unke sath rehti hai?", "answer": "parchhai"},
    {"riddle": "Vo kya hai jo lamba hai aur gaadi chalate waqt haath mein pakda jata hai?", "answer": "gear"},
    {"riddle": "Aisi kaun si jagah hai jahan sabhi log chup chap baithte hain?", "answer": "cinema hall"},
    {"riddle": "Vo kya hai jo gol hai aur ladkiyan use apne kaan mein pehanti hain?", "answer": "baali"},
    {"riddle": "Ladkiyon ke paas aisa kya hai jo ladkon ke paas nahi hota?", "answer": "matritva"},
    {"riddle": "Vo kya hai jo lamba hai aur dono haathon se pakadkar chalaya jata hai?", "answer": "steering"},
    {"riddle": "Aisi kaun si cheez hai jo shadi ke baad har ladki ko milti hai?", "answer": "naya ghar"}
]
