# easy.py

riddles = [
    {"riddle": "Ek qile ke do hi darwaze, andar baithe kaale raaje?", "answer": "laung"},
    {"riddle": "Kaan marodo paani dunga, koi rupya nahi loonga?", "answer": "nal"},
    {"riddle": "Lal-lal rang hai, bada hi rasila hai, phal ka vo raja hai?", "answer": "aam"},
    {"riddle": "Bimar nahi rehti phir bhi khati hai goli, darr jaate hain sab?", "answer": "bandook"},
    {"riddle": "Safed murgi hari pooch, na jaan paaye toh mummy se pooch?", "answer": "mooli"},
    {"riddle": "Chaar paanv hain par chal nahi sakti, bina bataye hil nahi sakti?", "answer": "kursi"},
    {"riddle": "Gol hai par gend nahi, roshni deta hai par suraj nahi?", "answer": "bulb"},
    {"riddle": "Paani mein peda hota hai, paani mein hi mar jata hai, rasoi ki jaan hai?", "answer": "namak"},
    {"riddle": "Kaala hai par koyla nahi, lamba hai par saanp nahi, sir par rehta hai?", "answer": "baal"},
    {"riddle": "Hawa mein udta hai par pakshi nahi, dori se bandha hai?", "answer": "gubbara"},
    {"riddle": "Khaate hain par chabate nahi, nigalte hain par thukte nahi?", "answer": "kasam"},
    {"riddle": "Subah-subah aata hai, shaam ko chala jata hai, ujala lata hai?", "answer": "suraj"},
    {"riddle": "Chhoti si hai par bade-badon ko rula deti hai?", "answer": "pyaaz"},
    {"riddle": "Peele rang ka fal hoon, bandaron ka main pyara hoon?", "answer": "kela"},
    {"riddle": "Ek raat mein paida hoti hoon, suraj aate hi mar jaati hoon?", "answer": "oss"},
    {"riddle": "Do sundar ladke, ek jaise rang ke, ek khoye toh dusra kaam na aaye?", "answer": "joota"},
    {"riddle": "Hath mein hai par pakad nahi sakte, behta jata hai?", "answer": "samay"},
    {"riddle": "Kaan hain par behri hai, munh hai par bolti nahi, ladkiyon ki pyari?", "answer": "gudiya"},
    {"riddle": "Kaali hai par raat nahi, chalti hai par paer nahi, dhup me sath deti hai?", "answer": "parchhai"},
    {"riddle": "Kato toh badhta jata hai, kya hai vo?", "answer": "baal"},
    {"riddle": "Sone ki vo cheez hai par mile na sunar ki dukaan par, sone ke kaam aaye?", "answer": "charpai"},
    {"riddle": "Ek raja ki aisi rani, jiske dum par rehta paani?", "answer": "diya"},
    {"riddle": "Aisa kaun sa fal hai jismein taala aur chabi dono aate hain?", "answer": "lauki"},
    {"riddle": "Hath mein aaye toh saaf kare, pani mile toh jhaag kare?", "answer": "sabun"},
    {"riddle": "Jitna chabao utni hi badi hoti jaye, munh mein maza laye?", "answer": "chingum"},
    {"riddle": "Aankhein hain par andhi hai, per hain par chalti nahi?", "answer": "gudiya"},
    {"riddle": "Ek chidiya aisi, jo baitho toh bole, chalti jaye toh tulti jaye?", "answer": "tarazu"},
    {"riddle": "Kagaz ka hai ghora, dhage ki hai lagaam, udao toh aasmaan chhue?", "answer": "patang"},
    {"riddle": "Chhota sa hai ghar, usme rehte hain 30-40 bhai, aag lagate hain?", "answer": "maachis"},
    {"riddle": "Ek pelee deewar, uske andar meethe ras ki dhaar?", "answer": "ganna"},
    {"riddle": "Kholon toh sab kuch dikhaye, band karon toh andhera chhaye?", "answer": "aankh"},
    {"riddle": "Paani peete hi mar jaati hai, batao kaun?", "answer": "pyaas"},
    {"riddle": "Sabhi ke paas hai, koi chhu nahi sakta, badalti rehti hai?", "answer": "umar"},
    {"riddle": "Lal hai par mirch nahi, chalti hai par gadi nahi, khoon badhati hai?", "answer": "gaajar"},
    {"riddle": "Chhota sa hai kuan, usme se nikalta hai dhuan?", "answer": "beedi"},
    {"riddle": "Gol gol chakkar jaisa, meetha ras bhara hai kaisa?", "answer": "jalebi"},
    {"riddle": "Bina peron ke chalti hai, sabko samay batati hai?", "answer": "ghadi"},
    {"riddle": "Ek rani aisi jiske sir par taaj, mithi hai vo sabki raaj?", "answer": "mithai"},
    {"riddle": "Ghar ke andar rehta hai, dhup mein bahar nikalta hai?", "answer": "chata"},
    {"riddle": "Kaala munh hai mera, safed pet par chalta hoon?", "answer": "pen"},
    {"riddle": "Gol gol hai mera badan, andar hai meetha ras-kadam?", "answer": "rasgulla"},
    {"riddle": "Char paanv par baithti hai, chal nahi sakti?", "answer": "mej"},
    {"riddle": "Hawa khaye toh zinda rahe, paani piye toh mar jaye?", "answer": "aag"},
    {"riddle": "Ek lathi aisi, jismein bhara paani jaisi?", "answer": "ganna"},
    {"riddle": "Aisa kaun sa desh hai jahan sirf ek hi ped hai?", "answer": "registan"},
    {"riddle": "Boodha ho ya bachcha, sabko deta hai dudh sachha?", "answer": "bhains"},
    {"riddle": "Khaane mein aata hoon kaam, ulta likho toh fal ka naam?", "answer": "chana"},
    {"riddle": "Ek choti si dibbi, usme band hai bijli?", "answer": "torch"},
    {"riddle": "Aisa kaun sa shahar hai jise hum kha sakte hain?", "answer": "puri"},
    {"riddle": "Subah ko chhota, dopehar ko bada, shaam ko phir chhota?", "answer": "parchhai"},
    {"riddle": "Pankh hain par udti nahi, paani mein hi rehti hai?", "answer": "machli"},
    {"riddle": "Aapke paas hai par dusre iska use zyada karte hain?", "answer": "naam"},
    {"riddle": "Ghar mein aate hi roshni kar deta hai, chhota sa hai?", "answer": "diya"},
    {"riddle": "Bina bolti hai, sab kuch keh jaati hai, gyan ka sagar hai?", "answer": "kitaab"},
    {"riddle": "Do per hain par chal nahi sakta, hawa mein udta hai?", "answer": "chashma"},
    {"riddle": "Peeli peeli hoti hai, sabji mein swad lati hai?", "answer": "haldi"},
    {"riddle": "Khane se pehle nahi dikhti, thokar khane par milti hai?", "answer": "akal"},
    {"riddle": "Safed badan hai, meetha mann hai, thand mein sabka pyara hai?", "answer": "dudh"},
    {"riddle": "Sir par patta, badan par kanta, fal hai meetha?", "answer": "ananas"},
    {"riddle": "Deewar par chalti hai, keede-makode khati hai?", "answer": "chipkali"},
    {"riddle": "Munh kholo toh bolta hoon, band karo toh chup hoon?", "answer": "insan"},
    {"riddle": "Ek ped par 12 daali, har daali par 30 patte?", "answer": "saal"},
    {"riddle": "Aisi kaun si cheez hai jo tootne par hi kaam aati hai?", "answer": "anda"},
    {"riddle": "Sabse chhota jaanwar kaun sa hai jo ghar mein milta hai?", "answer": "cheenti"},
    {"riddle": "Lal hai rang mera, falon mein ginte hain, rasila hoon?", "answer": "anar"},
    {"riddle": "Kaan marodo toh chalta hoon, roshni failata hoon?", "answer": "switch"},
    {"riddle": "Kaale hain par bhaalo nahi, udte hain par pakshi nahi?", "answer": "badal"},
    {"riddle": "Aisa kaun sa kanta hai jo chubhta nahi, par swad deta hai?", "answer": "chaukanta"},
    {"riddle": "Aasmaan se girti hai, mitti mein mil jaati hai?", "answer": "baarish"},
    {"riddle": "Hari hai zameen par, laal hai bazaar mein?", "answer": "mehandi"},
    {"riddle": "Dikhne mein gol hai, andar se lal hai, garmi ka tohfa hai?", "answer": "tarbuj"},
    {"riddle": "Munh nahi hai par bolti hai, kaan nahi par sunti hai?", "answer": "akashwani"},
    {"riddle": "Bina hath-paer ke sabko darati hai, ghar mein ghus jaati hai?", "answer": "hawa"},
    {"riddle": "Lal peeli hoti hai, kitchen ki raaj hai, teekhi hoti hai?", "answer": "mirch"},
    {"riddle": "Ek baap ne apne bete ko ek cheez di aur kaha: Bhuk lage toh kha lena, pyaas lage toh pee lena, thand lage toh jala lena?", "answer": "nariyal"},
    {"riddle": "Ek phal aisa jiska naam lene se darr lagta hai?", "answer": "bhayankar"},
    {"riddle": "Safed chaadar par kaale daane, padhne wale hi isko jaane?", "answer": "kitaab"},
    {"riddle": "Din mein soye, raat ko roye, jitna roye utna khoye?", "answer": "mombatti"},
    {"riddle": "Kaala hai par koyla nahi, gol hai par suraj nahi, gaadi mein chalta hai?", "answer": "tyre"},
    {"riddle": "Aisa kaun sa shabdh hai jise hum likhte hain par padhte nahi?", "answer": "nahi"},
    {"riddle": "Sukha ho toh 2 kilo, geela ho toh 1 kilo, jal jaye toh 3 kilo?", "answer": "sulphur"},
    {"riddle": "Aisi kaun si cheez hai jo upar jaati hai par neeche nahi aati?", "answer": "umar"},
    {"riddle": "Kuaan hai par paani nahi, bada hai par raaja nahi?", "answer": "pet"},
    {"riddle": "Aisa kaun sa room hai jisme khidki darwaza nahi hota?", "answer": "mushroom"},
    {"riddle": "Bina pankh ke udti hai, bina hath ke ladti hai?", "answer": "patang"},
    {"riddle": "Do aisi aankhein hain jo sab kuch dekhti hain par aapas mein nahi milti?", "answer": "chashma"},
    {"riddle": "Kaale rang ka ek parinda, bolta hai bada hi ganda?", "answer": "kauwa"},
    {"riddle": "Aisa kaun sa fal hai jo do saal mein pakta hai?", "answer": "ananas"},
    {"riddle": "Ek haath ka jaanwar, sabko darata hai?", "answer": "haathi"},
    {"riddle": "Safed ghar ke andar peela chor baithe hai?", "answer": "anda"},
    {"riddle": "Lamba badan hai, sir par taaj hai, jungle ka vo baaj hai?", "answer": "shere"},
    {"riddle": "Khane mein swad badhata hoon, pilaya jata hoon, garmi door karta hoon?", "answer": "nimbu"},
    {"riddle": "Aisa kaun sa phool hai jismein khushboo nahi hoti?", "answer": "aprajita"},
    {"riddle": "Ek chhota sa chor, ghar-ghar karta shor?", "answer": "chuha"},
    {"riddle": "Aisa kaun sa ped hai jis par chadha nahi ja sakta?", "answer": "kela"},
    {"riddle": "Ghar mein aati hai par dikhti nahi, sabko thandak deti hai?", "answer": "hawa"},
    {"riddle": "Ek choti si sui, sabko jode rakhe?", "answer": "dhaga"},
    {"riddle": "Aisa kaun sa gehna hai jo sunar nahi banata?", "answer": "phoolon ka haar"},
    {"riddle": "Khula chodo toh bhag jaye, pakdo toh hath na aaye?", "answer": "hawa"},
    {"riddle": "Saal mein ek baar aata hai, sabko khush kar jata hai?", "answer": "janamdin"}
]
