# funny.py

riddles = [
    {"riddle": "Aisa kaun sa shahar hai jise hum kha sakte hain?", "answer": "puri"},
    {"riddle": "Vo kaun sa kanta hai jo chubhata nahi par log use shaunk se khaate hain?", "answer": "chaukanta"},
    {"riddle": "Aisa kaun sa room hai jismein na toh koi khidki hoti hai aur na hi koi darwaza?", "answer": "mushroom"},
    {"riddle": "Aisi kaun si sabzi hai jismein taala aur chabi dono aate hain?", "answer": "lauki"},
    {"riddle": "Aisa kaun sa fal hai jo ladki ka naam bhi hai?", "answer": "seetafal"},
    {"riddle": "Kaun sa shahar hai jise pehna ja sakta hai?", "answer": "pant"},
    {"riddle": "Ek aadmi ne ek hi haath se 10 gaadiyon ko rok diya, batao vo kaun hai?", "answer": "traffic policeman"},
    {"riddle": "Aisa kaun sa kuan hai jismein koi pani nahi hota, phir bhi sab doobte hain?", "answer": "khwab"},
    {"riddle": "Aisi kaun si cheez hai jiske paas teeth (daant) hain par vo chaba nahi sakti?", "answer": "kanghi"},
    {"riddle": "Vo kya hai jo hamesha aapke peeche rehta hai par aap use dekh nahi sakte?", "answer": "beeta kal"},
    {"riddle": "Kaun sa insaan hai jo bina thake 24 ghante kaam karta hai aur ek rupya nahi leta?", "answer": "ghadi"},
    {"riddle": "Aisa kaun sa shabdh hai jise likhte hain 'galat' par padhte hain 'galat'?", "answer": "galat"},
    {"riddle": "Kaun si cheez hai jo sirf upar jaati hai aur kabhi neeche nahi aati?", "answer": "umar"},
    {"riddle": "Agar ek billi ne do ande diye, toh unme se kya niklega?", "answer": "kuch nahi"},
    {"riddle": "Aisa kaun sa driver hai jise license ki zaroorat nahi hoti?", "answer": "screwdriver"},
    {"riddle": "Kaun sa fal hai jo do saal mein pakta hai?", "answer": "ananas"},
    {"riddle": "Aisi kaun si cheez hai jo tootne ke baad hi kaam aati hai?", "answer": "anda"},
    {"riddle": "Kaun sa shahar hai jise ulta likho toh ek fal ka naam banta hai?", "answer": "chana"},
    {"riddle": "Aisa kya hai jo paani mein girti hai toh geeli nahi hoti?", "answer": "parchhai"},
    {"riddle": "Ek insaan bina soye 8 din kaise reh sakta hai?", "answer": "raat ko sokar"},
    {"riddle": "Kaun sa kanta machli pakadne ke kaam aata hai?", "answer": "bansi"},
    {"riddle": "Aisa kaun sa pinjra hai jismein koi pakshi nahi reh sakta?", "answer": "pasli"},
    {"riddle": "Vo kya hai jo aag mein nahi jalti aur paani mein nahi doobti?", "answer": "baraf"},
    {"riddle": "Aisi kaun si cheez hai jo garm karne par jam jaati hai?", "answer": "anda"},
    {"riddle": "Ghar ka pahredar hoon par bina roti ke chalta hoon?", "answer": "taala"},
    {"riddle": "Aisa kya hai jiske paas jeebh nahi hai par bolta poora hai?", "answer": "paisa"},
    {"riddle": "Aisi kaun si cheez hai jo khareedte waqt kaali aur fenkte waqt safed hoti hai?", "answer": "koyla"},
    {"riddle": "Kaun sa phool hai jismein khushboo nahi hoti?", "answer": "aprajita"},
    {"riddle": "Aisa kaun sa ped hai jis par koi chadh nahi sakta?", "answer": "kela"},
    {"riddle": "Ek phal aisa jiska naam lene se darr lagta hai?", "answer": "bhayankar"},
    {"riddle": "Din mein soye, raat ko roye, jitna roye utna khoye?", "answer": "mombatti"},
    {"riddle": "Kaala munh hai mera, safed pet par chalta hoon?", "answer": "pen"},
    {"riddle": "Ek choti si sui, sabko jode rakhe par khud akeli rahe?", "answer": "sui"},
    {"riddle": "Gol gol hai mera badan, andar hai meetha ras-kadam?", "answer": "rasgulla"},
    {"riddle": "Aisa kaun sa kuan hai jismein paani hai par koi pee nahi sakta?", "answer": "aankh"},
    {"riddle": "Vo kaun sa pakshi hai jo zameen par kabhi pair nahi rakhta?", "answer": "hariyal"},
    {"riddle": "Aisi kaun si cheez hai jise ladkiyan pehanti bhi hain aur khati bhi hain?", "answer": "laung"},
    {"riddle": "Vo kaun si cheez hai jo sirf bolne se hi gayab ho jaati hai?", "answer": "khamoshi"},
    {"riddle": "Vo kya hai jo jitna zyaada paas aayega, utna hi kam dikhega?", "answer": "andhera"},
    {"riddle": "Aisi kaun si cheez hai jiske paas gardan hai par sir nahi hai?", "answer": "b बोतल"},
    {"riddle": "Vo kya hai jo poori duniya ghoomta hai par ek kone mein baitha rehta hai?", "answer": "ticket"},
    {"riddle": "Vo kaun hai jo humesha apna munh zameen par ghisata rehta hai?", "answer": "jhaadoo"},
    {"riddle": "Aisi kaun si jagah hai jahan nadiya hain par paani nahi, shahar hain par makan nahi?", "answer": "naksha"},
    {"riddle": "Aisa kaun sa janwar hai jo paani peete hi mar jata hai?", "answer": "kangaroo rat"},
    {"riddle": "Vo kaun hai jo sabko kapde pehnata hai par khud nanga rehta hai?", "answer": "sui"},
    {"riddle": "Kaun sa raja hai jiske paas na koi mahal hai na koi paisa?", "answer": "jungle ka raja"},
    {"riddle": "Aisi kaun si cheez hai jo paani peete hi mar jaati hai?", "answer": "pyaas"},
    {"riddle": "Kato toh badhta jata hai, kya hai vo?", "answer": "baal"},
    {"riddle": "Ek chhota sa chor, ghar-ghar karta shor?", "answer": "chuha"},
    {"riddle": "Aisa kaun sa gehna hai jo sunar nahi banata?", "answer": "phoolon ka haar"},
    {"riddle": "Saal mein ek baar aata hai, sabko khush kar jata hai?", "answer": "janamdin"},
    {"riddle": "Aisi kaun si cheez hai jo dhoop mein nahi sukh sakti?", "answer": "pasina"},
    {"riddle": "Aisa kya hai jise aap ek baar khakar dobara nahi khana chahte?", "answer": "dhokha"},
    {"riddle": "Kaan hain par behra hoon, patta hoon par ped nahi hoon?", "answer": "kaan"},
    {"riddle": "Chhota sa hai afsar, chhat par baitha hai sar par?", "answer": "chata"},
    {"riddle": "Hari dandi, laal kamaan, tauba tauba kare insan?", "answer": "mirch"},
    {"riddle": "Char khambe jaisa badan, chalti jaise koi pavan?", "answer": "haathi"},
    {"riddle": "Kanch ke kamre mein band hai ek rani, roshni deti hai?", "answer": "bulb"},
    {"riddle": "Aisi kaun si cheez hai jo paida hote hi udne lagti hai?", "answer": "dhuan"},
    {"riddle": "Hath mein hai shor, khichlo toh naache chor?", "answer": "lattu"},
    {"riddle": "Hawa se halka hoon, par lakho log mujhe pakad nahi sakte?", "answer": "parchhai"},
    {"riddle": "Char kaanv hain par chal nahi sakta, sona sabko sikhata hai?", "answer": "bed"},
    {"riddle": "Chhoti si larki, lal ghagra pehne khari?", "answer": "mirch"},
    {"riddle": "Kala dhan, safed mann, batao kaun?", "answer": "til"},
    {"riddle": "Aisi kaun si cheez hai jise jitna kheenchoge vo utni hi chhoti hoti jayegi?", "answer": "cigarette"},
    {"riddle": "Bina peron ke chalti hai aur bina hatho ke sab kuch badal deti hai?", "answer": "kismat"},
    {"riddle": "Aisa kaun sa ped hai jo sabse zyaada oxygen deta hai?", "answer": "peepal"},
    {"riddle": "Aisa kaun sa shabdh hai jise poora desh ek hi tarah se bolta hai?", "answer": "namaste"},
    {"riddle": "Vo kya hai jo paani mein rehkar bhi kabhi geela nahi hota?", "answer": "tel"},
    {"riddle": "Aisi kaun si cheez hai jo humesha girti rehti hai par kabhi toot ti nahi?", "answer": "jarna"},
    {"riddle": "Kaun sa aesa bartan hai jo tootne par hi kaam aata hai?", "answer": "anda"},
    {"riddle": "Ek billi kuyein mein gir gayi, ab vo kaise niklegi?", "answer": "geeli hokar"},
    {"riddle": "Aisa kaun sa janwar hai jo jute pehan kar sota hai?", "answer": "ghora"},
    {"riddle": "Kaun sa shahar hai jahan sabse zyaada kele milte hain?", "answer": "hajipur"},
    {"riddle": "Aisi kaun si cheez hai jise log peet te hain par maza aata hai?", "answer": "dholak"},
    {"riddle": "Kaun sa fal hai jiske pet mein daant hote hain?", "answer": "anar"},
    {"riddle": "Aisa kaun sa gate hai jismein koi ghus nahi sakta?", "answer": "colgate"},
    {"riddle": "Kaun sa button hai jise dabane par bhi light nahi jalti?", "answer": "shirt ka button"},
    {"riddle": "Aisa kaun sa bank hai jahan paisa nahi milta?", "answer": "blood bank"},
    {"riddle": "Kaun sa kanta hai jo sabko pasand aata hai?", "answer": "chaukanta"},
    {"riddle": "Aisi kaun si cheez hai jiske paas haath hain par ungliyan nahi?", "answer": "ghadi"},
    {"riddle": "Kaun sa kuan hai jismein paani nahi shabdh hote hain?", "answer": "shabdh kosh"},
    {"riddle": "Aisa kya hai jo subah peda hota hai aur shaam ko mar jata hai?", "answer": "akhbar"},
    {"riddle": "Kaun si nadiya hai jahan paani nahi chanti behti hai?", "answer": "chai"},
    {"riddle": "Aisi kaun si machli hai jo tair nahi sakti?", "answer": "dead fish"},
    {"riddle": "Kaun sa pen hai jisse hum likh nahi sakte?", "answer": "penicillin"},
    {"riddle": "Aisa kaun sa cup hai jo tootne par bhi chae pee sakta hai?", "answer": "world cup"},
    {"riddle": "Kaun sa taaj hai jo kisi raja ke sir par nahi hota?", "answer": "sartaj"},
    {"riddle": "Aisi kaun si sabzi hai jo bolti boora hai?", "answer": "karela"},
    {"riddle": "Kaun sa patthar hai jo paani mein nahi doobta?", "answer": "pumice"},
    {"riddle": "Aisa kaun sa kela hai jo khaya nahi jata?", "answer": "chhilka"},
    {"riddle": "Kaun sa ped hai jis par kapde ugte hain?", "answer": "kapas"},
    {"riddle": "Aisi kaun si cheez hai jo aati hai par dikhti nahi?", "answer": "neend"},
    {"riddle": "Kaun sa chor hai jo sona churata hai par chor nahi kahlata?", "answer": "sonar"},
    {"riddle": "Aisa kaun sa aam hai jo khaya nahi jata?", "answer": "badam"},
    {"riddle": "Kaun sa rasta hai jahan koi gaadi nahi chal sakti?", "answer": "akash marg"},
    {"riddle": "Aisi kaun si chabi hai jo koi taala nahi kholti?", "answer": "monkey wrench"},
    {"riddle": "Kaun sa pakshi hai jo udta hai par par nahi hote?", "answer": "chamgadar"},
    {"riddle": "Aisa kaun sa chasma hai jo bina aakhon ke kaam karta hai?", "answer": "dourbin"},
    {"riddle": "Kaun si sabzi hai jismein ek desh ka naam hai?", "answer": "arbi"}
]
