# hard.py

riddles = [
    {"riddle": "Aisi kaun si cheez hai jise hum niglein toh zinda rahein, par vo humein nigle toh mar jaayein?", "answer": "paani"},
    {"riddle": "Vo kaun si aisi cheez hai jo paida toh samundar mein hoti hai par rehti aapke ghar mein hai?", "answer": "namak"},
    {"riddle": "Aise kaun se do bhai hain jo har waqt ek dusre ko dekhte hain, par kabhi aapas mein mil nahi paate?", "answer": "aankhein"},
    {"riddle": "Ooncha udta hai par aasmaan nahi chhu pata, pankh hain par udne ke kaam nahi aate?", "answer": "shuturmurg"},
    {"riddle": "Aisa kaun sa kuan hai jismein paani toh hai par koi pee nahi sakta?", "answer": "aankh"},
    {"riddle": "Aisi kaun si cheez hai jo khareedte waqt kaali, istemaal karte waqt laal aur fenkte waqt safed hoti hai?", "answer": "koyla"},
    {"riddle": "Lal ghora ruka rahe, kala ghora bhaag jaye. Batao kya?", "answer": "aag aur dhuan"},
    {"riddle": "Aisi kaun si cheez hai jo garm karne par jam jaati hai?", "answer": "anda"},
    {"riddle": "Aisa kya hai jo jitna bada hoga, utna hi kam dikhega?", "answer": "andhera"},
    {"riddle": "Ghar ke andar bhi hai aur bahar bhi hai, par uske bina ghar aadhura hai?", "answer": "darwaza"},
    {"riddle": "Vo kya hai jo aapke paas humesha rehti hai par aap use chhu nahi sakte?", "answer": "parchhai"},
    {"riddle": "Aisi kaun si cheez hai jo subah ko char taango par, dopehar ko do taango par aur shaam ko teen taango par chalta hai?", "answer": "manushya"},
    {"riddle": "Bina haad-maans ka ek parinda, aasmaan mein kare basera, dor se bandha rehna uski taqdeer?", "answer": "patang"},
    {"riddle": "Ek gufa mein 32 chor, din raat karte hain shor, phir bhi sab ek saath rehte hain?", "answer": "daant"},
    {"riddle": "Aisi kaun si cheez hai jo aati hai par kabhi wapas nahi jaati?", "answer": "maut"},
    {"riddle": "Vo kaun hai jo poore ek mahine baad aapke paas aati hai aur sirf 24 ghante rehkar chali jaati hai?", "answer": "tareekh"},
    {"riddle": "Aisi kaun si cheez hai jo paani mein girti hai toh geeli nahi hoti?", "answer": "parchhai"},
    {"riddle": "Ek aisi cheez ka naam batao jo tootne par hi zyaada kaam aati hai?", "answer": "anda"},
    {"riddle": "Vo kya hai jise aap jina zyaada safed karenge, vo utna hi ganda kahlayega?", "answer": "blackboard"},
    {"riddle": "Aisi kaun si cheez hai jise log kaatate hain, peesate hain, baantate hain par khaate nahi hain?", "answer": "taash"},
    {"riddle": "Ek phool hai kale rang ka, sir par sada suhaye, tej dhup mein khil jata hai, chhav dekh murjhaye?", "answer": "chata"},
    {"riddle": "Do aisi behnein hain jo ek saath paida hoti hain par dono ke beech mein ek pahad hota hai?", "answer": "aankhein"},
    {"riddle": "Aisa kaun sa kuan hai jismein koi bhi doob nahi sakta?", "answer": "mrit sagar"},
    {"riddle": "Aisi kaun si cheez hai jo chalti rehti hai par kabhi apni jagah se aage nahi badhti?", "answer": "ghadi"},
    {"riddle": "Vo kya hai jo subah ko paidal chalta hai aur raat ko aasmaan mein sota hai?", "answer": "suraj"},
    {"riddle": "Aisa kaun sa shabdh hai jise humesha 'galat' hi padha jata hai?", "answer": "galat"},
    {"riddle": "Vo kaun sa shahar hai jo do aksharon ka hai aur jise pehanne ke kaam mein laya jata hai?", "answer": "pant"},
    {"riddle": "Aisi kaun si cheez hai jo bina pairon ke tezi se daudti hai aur kabhi thakti nahi?", "answer": "nadi"},
    {"riddle": "Ek aisi cheez jo sone ki hai par sunar ki dukaan par nahi milti?", "answer": "charpai"},
    {"riddle": "Aisi kaun si cheez hai jo humesha badhti rehti hai par kabhi kam nahi hoti?", "answer": "umar"},
    {"riddle": "Vo kya hai jo roshni mein aapka sath nibhati hai par andhere mein chhod jaati hai?", "answer": "parchhai"},
    {"riddle": "Aisi kaun si sabzi hai jismein ek shahar ka naam chhupa hai?", "answer": "shimla mirch"},
    {"riddle": "Ek ped par 12 daaliyan hain, har daali par 30 ghosle hain, har ghosle mein 7 ande hain?", "answer": "calendar"},
    {"riddle": "Aisi kaun si cheez hai jo paida hote hi aasmaan mein udne lagti hai?", "answer": "dhuan"},
    {"riddle": "Vo kya hai jo aapko ek baar khakar dobara nahi khana chahte par phir bhi khaate hain?", "answer": "dhokha"},
    {"riddle": "Aisa kaun sa taala hai jo kabhi chabi se nahi khulta?", "answer": "digital lock"},
    {"riddle": "Vo kya hai jo aana chahe par hum rokte hain, aa jaye toh sab beh jata hai?", "answer": "aansu"},
    {"riddle": "Aisa kaun sa ped hai jiske paas lakdi nahi hoti?", "answer": "kela"},
    {"riddle": "Kaala munh hai mera, safed pet par chalta hoon, gyan failata hoon?", "answer": "pen"},
    {"riddle": "Khaane mein aata hoon kaam, ulta likho toh ek fal ka naam?", "answer": "chana"},
    {"riddle": "Bina pankh ke udti hai, bina haath ke ladti hai, aasmaan mein rehti hai?", "answer": "patang"},
    {"riddle": "Aisa kaun sa desh hai jahan ek bhi saanp nahi paya jata?", "answer": "ireland"},
    {"riddle": "Boodha ho ya bachcha, sabko deta hai gyan sachha?", "answer": "kitaab"},
    {"riddle": "Sukha ho toh 2 kilo, geela ho toh 1 kilo, jal jaye toh 3 kilo?", "answer": "sulphur"},
    {"riddle": "Aisa kaun sa phool hai jismein koi khushboo nahi hoti?", "answer": "aprajita"},
    {"riddle": "Ek chhota sa chor, ghar-ghar karta shor, billi se darta hai?", "answer": "chuha"},
    {"riddle": "Aisa kaun sa gehna hai jo sunar nahi banata?", "answer": "phoolon ka haar"},
    {"riddle": "Saal mein ek baar aata hai, sabko khush kar jata hai?", "answer": "janamdin"},
    {"riddle": "Aisi kaun si cheez hai jo dhoop mein nahi sukh sakti?", "answer": "pasina"},
    {"riddle": "Chhota sa hai afsar, chhat par baitha hai sar par, baarish mein sath deta hai?", "answer": "chata"},
    {"riddle": "Char khambe jaisa badan, chalti jaise koi pavan, lambi naak?", "answer": "haathi"},
    {"riddle": "Aisa kaun sa fal hai jo kachha hone par meetha aur pakne par khatta lagta hai?", "answer": "ananas"},
    {"riddle": "Ghar ka pahredar hoon, bina rotee ke chalta hoon, lohe ka hoon?", "answer": "taala"},
    {"riddle": "Paani se nikla ek aesa prani, jiske sir par haath lagao toh ban jaye paani?", "answer": "baraf"},
    {"riddle": "Aisi kaun si cheez hai jo bina pairon ke chadhti bhi hai aur utarti bhi hai?", "answer": "sharab"},
    {"riddle": "Char kaanv hain par chal nahi sakta, sona sabko sikhata hai?", "answer": "bed"},
    {"riddle": "Aisa kya hai jiske paas jeebh nahi hai par bolta poora hai?", "answer": "rupaye"},
    {"riddle": "Chhoti si larki, lal ghagra pehne khari, teekhi hai?", "answer": "mirch"},
    {"riddle": "Kala dhan, safed mann, batao kaun?", "answer": "til"},
    {"riddle": "Aisi kaun si cheez hai jo khareedte waqt hari par dhone par laal ho jaati hai?", "answer": "mehandi"},
    {"riddle": "Kaala hai badan par bhalu nahi, chalta hai par gadi nahi, chhat par rehta hai?", "answer": "tanki"},
    {"riddle": "Aisi kaun si cheez hai jise jitna kheenchoge vo utni hi chhoti hoti jayegi?", "answer": "cigarette"},
    {"riddle": "Ek shabdh se banoon main, sabko rasta dikhaoon main, gol-gol ghoomoon main?", "answer": "compass"},
    {"riddle": "Vo kaun sa pakshi hai jo zameen par kabhi pair nahi rakhta?", "answer": "hariyal"},
    {"riddle": "Aisi kaun si cheez hai jise ladkiyan pehanti bhi hain aur khati bhi hain?", "answer": "laung"},
    {"riddle": "Ek insaan bina soye 8 din kaise reh sakta hai?", "answer": "raat ko sokar"},
    {"riddle": "Vo kaun si cheez hai jo sirf bolne se hi gayab ho jaati hai?", "answer": "khamoshi"},
    {"riddle": "Aisi kaun si nadiya hai jahan paani nahi balki sona behta hai?", "answer": "svarnarekha"},
    {"riddle": "Bina peron ke chalti hai aur bina hatho ke sab kuch badal deti hai?", "answer": "kismat"},
    {"riddle": "Aisa kaun sa pinjra hai jismein koi pakshi nahi rehta?", "answer": "pasli"},
    {"riddle": "Vo kaun sa janwar hai jo bol nahi sakta par sab kuch samajhta hai?", "answer": "kutta"},
    {"riddle": "Aisi kaun si cheez hai jo aasmaan se girti hai par mitti mein gayab ho jaati hai?", "answer": "ole"},
    {"riddle": "Ek haath ki sui, sabko ek sath jode rakhe?", "answer": "dhaga"},
    {"riddle": "Kaala hai par raat nahi, chalti hai par per nahi, batao kya?", "answer": "siyahi"},
    {"riddle": "Aisa kaun sa ped hai jo sabse zyaada oxygen deta hai?", "answer": "peepal"},
    {"riddle": "Vo kya hai jo jitna zyaada paas aayega, utna hi kam dikhega?", "answer": "andhera"},
    {"riddle": "Aisi kaun si cheez hai jiske paas gardan hai par sir nahi hai?", "answer": "b बोतल"},
    {"riddle": "Ek baap ne beti ko ek phal diya aur bola: Bhuk lage toh kha lena, pyaas lage toh pee lena?", "answer": "nariyal"},
    {"riddle": "Aisa kaun sa desh hai jahan raat sirf 40 minute ki hoti hai?", "answer": "norway"},
    {"riddle": "Vo kya hai jo poori duniya ghoomta hai par ek kone mein hi baitha rehta hai?", "answer": "ticket"},
    {"riddle": "Aisi kaun si cheez hai jo kachhi ho toh hari, pak jaye toh laal aur sookh jaye toh kaali?", "answer": "mirch"},
    {"riddle": "Vo kaun hai jo humesha apna munh zameen par ghisata rehta hai?", "answer": "jhaadoo"},
    {"riddle": "Aisi kaun si jagah hai jahan nadiya hain par paani nahi, shahar hain par makan nahi?", "answer": "naksha"},
    {"riddle": "Vo kya hai jo aapse sab kuch le leta hai par aapko kuch nahi bolta?", "answer": "daku"},
    {"riddle": "Aisa kaun sa janwar hai jo paani peete hi mar jata hai?", "answer": "kangaroo rat"},
    {"riddle": "Vo kya hai jo badhta hi jata hai aur kabhi ghatta nahi?", "answer": "umar"},
    {"riddle": "Aisi kaun si cheez hai jise hum saaf karte hain toh vo kaali ho jaati hai?", "answer": "blackboard"},
    {"riddle": "Vo kaun sa phool hai jo 12 saal mein ek hi baar khilta hai?", "answer": "neelakurinji"},
    {"riddle": "Aisi kaun si cheez hai jo lohe ko kheench sakti hai par sone ko nahi?", "answer": "chumbak"},
    {"riddle": "Vo kya hai jo upar se neeche girti hai par kabhi chot nahi lagti?", "answer": "baarish"},
    {"riddle": "Aisa kaun sa fal hai jiske andar zehar paya jata hai?", "answer": "seb ke beej"},
    {"riddle": "Vo kya hai jo aag mein nahi jalti aur paani mein nahi doobti?", "answer": "baraf"},
    {"riddle": "Aisi kaun si cheez hai jo bina aag ke jalti hai?", "answer": "eershya"},
    {"riddle": "Vo kaun hai jo har kisi ka swagat karta hai par khud kabhi ghar nahi aata?", "answer": "pyadan"},
    {"riddle": "Aisi kaun si cheez hai jo paas ho toh dikhti nahi, door ho toh dhundhli ho jaati hai?", "answer": "nazar"},
    {"riddle": "Vo kya hai jo bina pankh ke udta hai aur bina peron ke daudta hai?", "answer": "dhuan"},
    {"riddle": "Aisa kaun sa shabdh hai jise poora desh ek hi tarah se bolta hai?", "answer": "namaste"},
    {"riddle": "Vo kya hai jo paani mein rehkar bhi kabhi geela nahi hota?", "answer": "tel"},
    {"riddle": "Aisi kaun si cheez hai jo humesha girti rehti hai par kabhi toot ti nahi?", "answer": "jarna"},
    {"riddle": "Vo kaun hai jo sabko kapde pehnata hai par khud nanga rehta hai?", "answer": "sui"}
]
