# math.py

riddles = [
    {"riddle": "Ek murgi ne border par anda diya. Vo anda kiska hoga, India ka ya Pakistan ka?", "answer": "murgi"},
    {"riddle": "Ek tokri mein 5 aam hain. Agar aapne 3 aam utha liye, toh aapke paas kitne aam bache?", "answer": "3"},
    {"riddle": "Ek kuyein mein 10 mendhak the. Agar 2 mar gaye, toh kuyein mein ab kitne mendhak bache?", "answer": "10"},
    {"riddle": "Agar ek ande ko ubalne mein 10 minute lagte hain, toh 5 andon ko ek saath ubalne mein kitna samay lagega?", "answer": "10 minute"},
    {"riddle": "Kaun sa aesa number (sankhya) hai jise ulta karne par uski value badh jaati hai?", "answer": "6"},
    {"riddle": "Ek over mein kitni balls phenki jaati hain? (Sirf sankhya likhein)", "answer": "6"},
    {"riddle": "Ek kile mein 10 darwaze hain, har darwaze par 2 pehredar hain. Total kitne pehredar hue?", "answer": "20"},
    {"riddle": "Agar 3 billiyan 3 chuhe 3 minute mein pakadti hain, toh 100 billiyan 100 chuhe kitne minute mein pakadengi?", "answer": "3"},
    {"riddle": "1 se 100 tak ki गिनती mein total kitne 9 aate hain? (Sirf sankhya likhein)", "answer": "20"},
    {"riddle": "Ek doctor ne aapko 3 goliya di aur kaha har aadhe ghante mein ek khana. Toh teeno goliya khatam hone mein kitna samay lagega?", "answer": "1 ghanta"},
    {"riddle": "Do baap aur do bete ek saath machli pakadne gaye. Unhone total 3 machliyan pakdi aur sabko 1-1 mili. Kaise?", "answer": "dada pita pota"},
    {"riddle": "Aapke paas 2 gaayein aur 2 bakriyan hain. Aapke kitne paer hain?", "answer": "2"},
    {"riddle": "Ek kamre ke chaar kone hain. Har kone mein ek billi baithi hai. Har billi ke samne 3 billiyan hain. Kamre mein total kitni billiyan hain?", "answer": "4"},
    {"riddle": "Agar ek kilo loha aur ek kilo rui ko upar se fenka jaye, toh zameen par pehle kaun girega?", "answer": "dono sath"},
    {"riddle": "Ek saal mein kitne mahine hote hain jismein 28 din aate hain?", "answer": "12"},
    {"riddle": "1 se 50 tak ki ginti mein kitne baar 5 aata hai?", "answer": "15"},
    {"riddle": "Ek ped par 10 pakshi baithe the. Ek shikari ne 1 ko goli maar di. Ped par ab kitne pakshi bache?", "answer": "0"},
    {"riddle": "Agar aapke paas 3 seb hain aur aapne 2 le liye, toh aapke paas kitne seb hain?", "answer": "2"},
    {"riddle": "Aisi kaun si sankhya hai jise kisi bhi number se multiply (guna) karo toh answer humesha 0 aata hai?", "answer": "0"},
    {"riddle": "Ek line mein 5 log khade hain. Aap peeche se dusre number par ho, toh aage se aapka kaun sa number hai?", "answer": "4"},
    {"riddle": "Ek din mein ek ghadi ki dono suiyan kitni baar ek dusre ke upar aati hain?", "answer": "22"},
    {"riddle": "Agar 1=5, 2=25, 3=125, 4=625 toh 5=? (Dhyan se sochein)", "answer": "1"},
    {"riddle": "Ek kile mein 50 sipahi the, unke liye 30 din ka khana tha. 10 din baad 20 sipahi chale gaye. Khana ab kitne din chalega?", "answer": "33"},
    {"riddle": "Ek auto mein 3 log baithe hain. Unke total kitne per hain?", "answer": "6"},
    {"riddle": "Ek cricket match mein agar ek batsman pehli 6 ball par 6 single leta hai, toh usne kitne over khele?", "answer": "1"},
    {"riddle": "Kaun sa aesa digit hai jise Roman mein likha nahi ja sakta?", "answer": "0"},
    {"riddle": "Agar ek diwar ko banane mein 8 din lagte hain toh usi diwar ko banane mein 4 logo ko kitna samay lagega?", "answer": "0"},
    {"riddle": "10 mein se aap kitni baar 2 ghata (subtract) sakte hain?", "answer": "1"},
    {"riddle": "Ek aadmi ke 6 bete hain aur har bete ki ek behan hai. Us aadmi ke total kitne bachche hain?", "answer": "7"},
    {"riddle": "Agar kal se pehle ka din mangalwar tha, toh parso kaun sa din hoga?", "answer": "shanivar"},
    {"riddle": "Ek khali tokri ka diameter 10 inch hai. Usme aap kitne seb rakh sakte hain?", "answer": "1"},
    {"riddle": "Ek kuyein ki gehrai 10 meter hai. Ek mendhak roz 3 meter upar chadhta hai aur 2 meter fisal jata hai. Vo kitne din mein bahar aayega?", "answer": "8"},
    {"riddle": "Do alag-alag digits ka sabse chhota sum (jod) kya ho sakta hai?", "answer": "1"},
    {"riddle": "Aap 8 ko 8 baar likhkar 1000 kaise bana sakte hain? (Jawab mein 'plus' likhein)", "answer": "plus"},
    {"riddle": "Ek ghadi mein 1 se 12 tak ke digits hain. Unka total sum kitna hoga?", "answer": "78"},
    {"riddle": "100 ka aadha kitna hota hai?", "answer": "50"},
    {"riddle": "Agar ek murgi 2 din mein 2 ande deti hai, toh 10 murgiyan 10 din mein kitne ande dengi?", "answer": "50"},
    {"riddle": "Ek triangle (trikon) mein kitne kone hote hain?", "answer": "3"},
    {"riddle": "Ek square (varg) mein kitni side (bhuja) hoti hain?", "answer": "4"},
    {"riddle": "Agar aap ek race mein daud rahe hain aur aapne dusre number wale ko peeche chhod diya, toh aap kaun se number par hain?", "answer": "2"},
    {"riddle": "1 se 10 tak ke numbers ko aapas mein multiply karne par end mein kitne 0 aayenge?", "answer": "2"},
    {"riddle": "Ek hafte mein kitne ghante hote hain?", "answer": "168"},
    {"riddle": "Ek kile mein 7 raaje, har raaje ki 7 raniyan, har rani ke 7 bachche. Total kitne log hue? (7x7x7)", "answer": "343"},
    {"riddle": "0 aur 100 ke beech mein kitne prime numbers hote hain?", "answer": "25"},
    {"riddle": "Agar aapke paas 4 jeb hain aur har jeb mein 2 sikke hain, toh total kitne sikke hain?", "answer": "8"},
    {"riddle": "Ek century (shatabdi) mein kitne saal hote hain?", "answer": "100"},
    {"riddle": "Agar ek mahine ki 3 tareekh ko somwar hai, toh usi mahine ki 24 tareekh ko kya hoga?", "answer": "somwar"},
    {"riddle": "Ek plane crash mein sabhi log mar gaye, par 2 log bach gaye. Kaise?", "answer": "shaadi shuda the"},
    {"riddle": "5 ko 5 baar likhkar 5 kaise banayenge?", "answer": "5"},
    {"riddle": "Ek tokar mein 6 kele hain, unhe 6 bachchon mein aisi baanto ki sabko 1 kela mile aur tokri mein bhi 1 bacha rahe?", "answer": "aakhri ko tokri sath di"},
    {"riddle": "Ek rectangle mein kitne corners hote hain?", "answer": "4"},
    {"riddle": "Ek hafte mein kitne din hote hain?", "answer": "7"},
    {"riddle": "9 ko 9 se guna karne par kya aata hai?", "answer": "81"},
    {"riddle": "Agar aap 100 mein se 10 ko minus karenge, toh kya bachega?", "answer": "90"},
    {"riddle": "Duniya ka sabse pehla number kaun sa hai?", "answer": "1"},
    {"riddle": "Ek ghante mein kitne seconds hote hain?", "answer": "3600"},
    {"riddle": "Leap year mein total kitne din hote hain?", "answer": "366"},
    {"riddle": "Ek meter mein kitne centimeter hote hain?", "answer": "100"},
    {"riddle": "Do digit ka sabse bada number kaun sa hota hai?", "answer": "99"},
    {"riddle": "Three digit ka sabse chhota number kaun sa hota hai?", "answer": "100"},
    {"riddle": "Agar ek kilo chawal ki keemat 40 rs hai, toh 250 gram ki kitni hogi?", "answer": "10"},
    {"riddle": "Ek haath mein 5 ungliyan hain, toh 10 haathon mein kitni hongi?", "answer": "50"},
    {"riddle": "Agar aapke paas 12 kele hain aur aapne 4 dosto ko barabar baant diye, toh sabko kitne mile?", "answer": "3"},
    {"riddle": "Ek cricket over mein kitni valid balls hoti hain?", "answer": "6"},
    {"riddle": "Ek din mein kitne ghante hote hain?", "answer": "24"},
    {"riddle": "Ek saal mein kitne hafte hote hain?", "answer": "52"},
    {"riddle": "Oda number (visam sankhya) kaun sa hai: 2, 4, 7, 8?", "answer": "7"},
    {"riddle": "Even number (sam sankhya) kaun sa hai: 1, 3, 5, 6?", "answer": "6"},
    {"riddle": "5 ka double kitna hota hai?", "answer": "10"},
    {"riddle": "100 ka 10 percent kitna hoga?", "answer": "10"},
    {"riddle": "Agar ek pen ki keemat 5 rs hai, toh 20 pens ki kitni hogi?", "answer": "100"},
    {"riddle": "Ek ghante mein kitne minute hote hain?", "answer": "60"},
    {"riddle": "Aadha ghanta mein kitne minute hote hain?", "answer": "30"},
    {"riddle": "15 aur 15 ka jod kitna hota hai?", "answer": "30"},
    {"riddle": "50 mein se 25 ghatao toh kya bachega?", "answer": "25"},
    {"riddle": "Ek saal mein kitne din hote hain (normal year)?", "answer": "365"},
    {"riddle": "Kaun sa number sabse chhota prime number hai?", "answer": "2"},
    {"riddle": "4 ka square (varg) kya hoga?", "answer": "16"},
    {"riddle": "9 ka square root (vargmool) kya hoga?", "answer": "3"},
    {"riddle": "10 ko 10 se multiply karo toh kya aayega?", "answer": "100"},
    {"riddle": "Ek dozen (darjan) mein kitni cheezein hoti hain?", "answer": "12"},
    {"riddle": "Half dozen (aadha darjan) mein kitni cheezein hoti hain?", "answer": "6"},
    {"riddle": "25 ka double kitna hota hai?", "answer": "50"},
    {"riddle": "50 ka double kitna hota hai?", "answer": "100"},
    {"riddle": "75 aur 25 ka jod kitna hota hai?", "answer": "100"},
    {"riddle": "5 standard match mein total kitne players khelte hain ek sath ground par?", "answer": "22"},
    {"riddle": "Ek cricket team mein kitne active playing players hote hain?", "answer": "11"},
    {"riddle": "Ek hat-trick mein kitne wickets hote hain?", "answer": "3"},
    {"riddle": "1000 mein kitne zero hote hain?", "answer": "3"},
    {"riddle": "10000 mein kitne zero hote hain?", "answer": "4"},
    {"riddle": "Ek lakh mein kitne zero hote hain?", "answer": "5"},
    {"riddle": "Maths mein '+' ka matlab kya hota hai?", "answer": "jod"},
    {"riddle": "Maths mein '-' ka matlab kya hota hai?", "answer": "ghatana"},
    {"riddle": "10 ka table 5 baar padhne par kya aayega?", "answer": "50"},
    {"riddle": "20 ka aadha kitna hota hai?", "answer": "10"},
    {"riddle": "30 ka teen-guna (triple) kya hoga?", "answer": "90"},
    {"riddle": "40 mein se 10 minus karo toh kya bachega?", "answer": "30"},
    {"riddle": "80 ka aadha kitna hota hai?", "answer": "40"},
    {"riddle": "90 aur 10 ka jod kya hoga?", "answer": "100"},
    {"riddle": "1000 ka aadha kitna hota hai?", "answer": "500"}
]
