# medium.py

riddles = [
    {"riddle": "Aisi kaun si cheez hai jo dhup mein paida hoti hai par chhav mein mar jaati hai?", "answer": "pasina"},
    {"riddle": "Kato toh khoon nahi, ukhado toh dard nahi. Batao kya?", "answer": "naakhun"},
    {"riddle": "Ek raja ki aisi rani, jiske dum par rehta paani?", "answer": "diya"},
    {"riddle": "Aisi kaun si jagah hai jahan 100 log jaate hain toh 99 hi wapas aate hain?", "answer": "shmashan"},
    {"riddle": "Vo kya hai jo aana chahe par hum rokte hain, aa jaye toh sab beh jata hai?", "answer": "aansu"},
    {"riddle": "Hath-paer sab gayab hain par chalti jati hai, sabko apna pata batati hai?", "answer": "chitti"},
    {"riddle": "Aisa kaun sa ped hai jiske paas lakdi nahi hoti?", "answer": "kela"},
    {"riddle": "Vo kya hai jo paas ho toh chain nahi, door ho toh sukoon nahi?", "answer": "paisa"},
    {"riddle": "Ek chhota sa bachcha, pet mein uske kanchha, batao kya?", "answer": "jamun"},
    {"riddle": "Ek aisi cheez jo upar bhi jaati hai aur neeche bhi, par apni jagah se hilti nahi?", "answer": "seedi"},
    {"riddle": "Aisi kaun si cheez hai jise jitna saaf karo, vo utni hi kaali hoti jaati hai?", "answer": "blackboard"},
    {"riddle": "Ooncha udta hai par aasmaan nahi chhu pata, pankh hain par udne ke kaam nahi aate?", "answer": "shuturmurg"},
    {"riddle": "Vo kaun sa shahar hai jiske naam mein ek fal ka naam aata hai?", "answer": "nagpur"},
    {"riddle": "Aisa kaun sa kuan hai jismein paani toh hai par koi pee nahi sakta?", "answer": "aankh"},
    {"riddle": "Jitna aage badhoge, utne hi peeche chhodte jaoge. Batao kya?", "answer": "kadam"},
    {"riddle": "Ek gufa mein 32 chor, din raat karte hain shor, batao kya?", "answer": "daant"},
    {"riddle": "Vo kya hai jo bolne se hi toot jaati hai?", "answer": "khamoshi"},
    {"riddle": "Aisi kaun si cheez hai jiske paas pankh nahi hain phir bhi vo udti hai?", "answer": "patang"},
    {"riddle": "Kaanch ki ek anokhi haveli, bina tel ke chalti hai paheli, ujala deti hai?", "answer": "bulb"},
    {"riddle": "Lal ghora ruka rahe, kala ghora bhaag jaye. Batao kya?", "answer": "aag aur dhuan"},
    {"riddle": "Aisi kaun si cheez hai jo paani peete hi mar jaati hai?", "answer": "pyaas"},
    {"riddle": "Vo kaun hai jo bina pairon ke bhagta hai aur kabhi wapas nahi aata?", "answer": "waqt"},
    {"riddle": "Do judwa bhai hain, dono ke ghar paas hain, par ek dusre ko dekh nahi sakte?", "answer": "aankhein"},
    {"riddle": "Aisi kaun si cheez hai jo humesha soti rehti hai par paani milte hi jag jaati hai?", "answer": "chuha"},
    {"riddle": "Hath mein hai par pakad nahi sakte, behta jata hai par rok nahi sakte?", "answer": "paani"},
    {"riddle": "Vo kya hai jo aapka apna hai par dusre log use aapse zyada use karte hain?", "answer": "naam"},
    {"riddle": "Ek choti si sui, sabko jode rakhe par khud akele rahe?", "answer": "sui"},
    {"riddle": "Aisa kaun sa ped hai jismein phal nahi lagta par sabji banti hai?", "answer": "sahjan"},
    {"riddle": "Hari thali mein laal dana, khane wale ko ho gaya gana?", "answer": "tarbuj"},
    {"riddle": "Safed deewar, na koi khidki na koi dwar, andar baitha ek rajkumar?", "answer": "anda"},
    {"riddle": "Bina paron ke udti hai, bina haath ke ladti hai?", "answer": "patang"},
    {"riddle": "Aisa kaun sa shabdh hai jise hum likhte hain par padhte nahi?", "answer": "nahi"},
    {"riddle": "Aisi kaun si cheez hai jo tootne par hi kaam aati hai?", "answer": "anda"},
    {"riddle": "Gol gol hai mera badan, andar hai meetha ras-kadam?", "answer": "rasgulla"},
    {"riddle": "Kaala munh hai mera, safed pet par chalta hoon?", "answer": "pen"},
    {"riddle": "Ek lathi aisi, jismein bhara paani jaisi?", "answer": "ganna"},
    {"riddle": "Aisa kaun sa desh hai jahan ek bhi saanp nahi paya jata?", "answer": "ireland"},
    {"riddle": "Boodha ho ya bachcha, sabko deta hai gyan sachha?", "answer": "kitaab"},
    {"riddle": "Khaane mein aata hoon kaam, ulta likho toh fal ka naam?", "answer": "chana"},
    {"riddle": "Ek choti si dibbi, usme band hai bijli?", "answer": "torch"},
    {"riddle": "Subah ko chhota, dopehar ko bada, shaam ko phir chhota?", "answer": "parchhai"},
    {"riddle": "Pankh hain par udti nahi, paani mein hi rehti hai?", "answer": "machli"},
    {"riddle": "Do per hain par chal nahi sakta, hawa mein udta hai?", "answer": "chashma"},
    {"riddle": "Peeli peeli hoti hai, sabji mein swad lati hai?", "answer": "haldi"},
    {"riddle": "Khane se pehle nahi dikhti, thokar khane par milti hai?", "answer": "akal"},
    {"riddle": "Sir par patta, badan par kanta, fal hai meetha?", "answer": "ananas"},
    {"riddle": "Deewar par chalti hai, keede-makode khati hai?", "answer": "chipkali"},
    {"riddle": "Aisi kaun si cheez hai jo jitna badhti hai, utni hi kam hoti hai?", "answer": "umar"},
    {"riddle": "Lal hai rang mera, falon mein ginte hain, rasila hoon?", "answer": "anar"},
    {"riddle": "Kaan marodo toh chalta hoon, roshni failata hoon?", "answer": "switch"},
    {"riddle": "Kaale hain par bhaalo nahi, udte hain par pakshi nahi?", "answer": "badal"},
    {"riddle": "Aasmaan se girti hai, mitti mein mil jaati hai?", "answer": "baarish"},
    {"riddle": "Hari hai zameen par, laal hai bazaar mein?", "answer": "mehandi"},
    {"riddle": "Munh nahi hai par bolti hai, kaan nahi par sunti hai?", "answer": "akashwani"},
    {"riddle": "Bina hath-paer ke sabko darati hai, ghar mein ghus jaati hai?", "answer": "hawa"},
    {"riddle": "Lal peeli hoti hai, kitchen ki raaj hai, teekhi hoti hai?", "answer": "mirch"},
    {"riddle": "Safed chaadar par kaale daane, padhne wale hi isko jaane?", "answer": "kitaab"},
    {"riddle": "Din mein soye, raat ko roye, jitna roye utna khoye?", "answer": "mombatti"},
    {"riddle": "Kaala hai par koyla nahi, gol hai par suraj nahi, tyre?", "answer": "tyre"},
    {"riddle": "Sukha ho toh 2 kilo, geela ho toh 1 kilo, jal jaye toh 3 kilo?", "answer": "sulphur"},
    {"riddle": "Aisi kaun si cheez hai jo upar jaati hai par neeche nahi aati?", "answer": "umar"},
    {"riddle": "Kuaan hai par paani nahi, bada hai par raaja nahi?", "answer": "pet"},
    {"riddle": "Aisa kaun sa room hai jisme khidki darwaza nahi hota?", "answer": "mushroom"},
    {"riddle": "Kaale rang ka ek parinda, bolta hai bada hi ganda?", "answer": "kauwa"},
    {"riddle": "Ek haath ka jaanwar, sabko darata hai?", "answer": "haathi"},
    {"riddle": "Safed ghar ke andar peela chor baithe hai?", "answer": "anda"},
    {"riddle": "Lamba badan hai, sir par taaj hai, jungle ka vo baaj hai?", "answer": "shere"},
    {"riddle": "Khane mein swad badhata hoon, pilaya jata hoon?", "answer": "nimbu"},
    {"riddle": "Aisa kaun sa phool hai jismein khushboo nahi hoti?", "answer": "aprajita"},
    {"riddle": "Ek chhota sa chor, ghar-ghar karta shor?", "answer": "chuha"},
    {"riddle": "Ghar mein aati hai par dikhti nahi, sabko thandak deti hai?", "answer": "hawa"},
    {"riddle": "Aisa kaun sa gehna hai jo sunar nahi banata?", "answer": "phoolon ka haar"},
    {"riddle": "Saal mein ek baar aata hai, sabko khush kar jata hai?", "answer": "janamdin"},
    {"riddle": "Sone ko palang nahi, na hi mahal banaye, ek rupya paas nahi phir bhi raja kahlaye?", "answer": "sher"},
    {"riddle": "Aisi kaun si cheez hai jo dhoop mein nahi sukh sakti?", "answer": "pasina"},
    {"riddle": "Aisa kya hai jise aap ek baar khakar dobara nahi khana chahte?", "answer": "dhokha"},
    {"riddle": "Kaan hain par behra hoon, patta hoon par ped nahi hoon?", "answer": "kaan"},
    {"riddle": "Chhota sa hai afsar, chhat par baitha hai sar par?", "answer": "chata"},
    {"riddle": "Hari dandi, laal kamaan, tauba tauba kare insan?", "answer": "mirch"},
    {"riddle": "Char khambe jaisa badan, chalti jaise koi pavan, lambi naak?", "answer": "haathi"},
    {"riddle": "Kanch ke kamre mein band hai ek rani, jab tak chalu hai deti hai roshni paani?", "answer": "bulb"},
    {"riddle": "Aisa kaun sa fal hai jo kachha hone par meetha aur pakne par khatta lagta hai?", "answer": "ananas"},
    {"riddle": "Ghar ka pahredar hoon, bina rotee ke chalta hoon?", "answer": "taala"},
    {"riddle": "Aisi kaun si cheez hai jo paida hote hi udne lagti hai?", "answer": "dhuan"},
    {"riddle": "Hath mein hai shor, khichlo toh naache chor?", "answer": "lattu"},
    {"riddle": "Ek aisi cheez jo subah dekho toh hari, dopehar ko kaali aur raat ko safed?", "answer": "billi"},
    {"riddle": "Paani se nikla ek aesa prani, jiske sir par haath lagao toh ban jaye paani?", "answer": "baraf"},
    {"riddle": "Aisi kaun si cheez hai jo bina pairon ke chadhti bhi hai aur utarti bhi hai?", "answer": "sharab"},
    {"riddle": "Hawa se halka hoon, par lakho log mujhe pakad nahi sakte?", "answer": "parchhai"},
    {"riddle": "Char kaanv hain par chal nahi sakta, sona sabko sikhata hai?", "answer": "bed"},
    {"riddle": "Aisa kya hai jiske paas jeebh nahi hai par bolta poora hai?", "answer": "rupaye"},
    {"riddle": "Chhoti si larki, lal ghagra pehne khari?", "answer": "mirch"},
    {"riddle": "Aisa kaun sa kanta hai jo machli pakadne ke kaam aata hai?", "answer": "bansi"},
    {"riddle": "Humesha chalta rehta hoon, rukta nahi hoon, sabko badalta hoon?", "answer": "waqt"},
    {"riddle": "Aisi kaun si cheez hai jo garm karne par jam jaati hai?", "answer": "anda"},
    {"riddle": "Kala dhan, safed mann, batao kaun?", "answer": "til"},
    {"riddle": "Ek ped par baithe hain 5 pakshi, 1 ko goli mari toh kitne bache?", "answer": "0"},
    {"riddle": "Aisa kya hai jo jitna bada hoga, utna hi kam dikhega?", "answer": "andhera"},
    {"riddle": "Aisi kaun si cheez hai jo khareedte waqt kaali, istemaal karte waqt laal aur fenkte waqt safed hoti hai?", "answer": "koyla"},
    {"riddle": "Ghar ke andar bhi hai aur bahar bhi hai, par uske bina ghar aadhura hai?", "answer": "darwaza"}
]
